### ISSUE TITLE
Webwork Script - Add Part Types 

### ISSUE THREAD

**Issue by Parsa-Rajabi** [open-resources/scripts#25]
For each part of the question, add a type:
- MC
- Numeric
- Multi-part
- If none of the above, type is `unknown`

Add a counter to keep track of # of parts in a question

```
part1:
  type: multiple-choice
  pl-customizations:
    weight: 1
```
